name: build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: atsushieno/aap-core/.github/workflows/build-sfz-bundle-app.yml@main
    secrets: inherit
